version: "3.3"
services:
  api:
    build: .
    ports:
      - "5000:5000"
  frontend:
    build: ./src/frontend
    stdin_open: true
    tty: true
    depends_on: [api]
    ports:
      - "3000:3000"
